name: Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update Dockerfile
        run: ./update-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
